// LOCALHOST
### DEFAULT
GET http://localhost:3000/
### GET ALL USERS
GET http://localhost:3000/users
### GET ONE USER
GET http://localhost:3000/users/646913d5128edb848723d22c
### CREATE USER
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "username":"dummyaccount",
    "displayname":"Dummy Account",
    "email":"ImJustHereToTest@mailplace.com",
    "password":"testingtesting123",
    "birthday":"12/25/1983"
    //"description":"Everyone will watch Splatoon 2 let's plays by Eggman"
}
### EDIT USER
PUT http://localhost:3000/users/647257cd576b56365908775c HTTP/1.1
Content-Type: application/json

{
    "username":"dummyaccount",
    //"displayname":"Dummy Account",
    "email":"CrashTestDummy@mailplace.com",
    "password":"testingtesting123",
    "birthday":"12/25/1983",
    "description":"Everyone will watch Splatoon 2 let's plays by Eggman"
}
### DELETE USER
DELETE http://localhost:3000/users/647257cd576b56365908775c HTTP/1.1

// RENDER
### DEFAULT
GET https://cse341-p02.onrender.com/
### GET ALL USERS
GET https://cse341-p02.onrender.com/users
### GET ONE USER
GET https://cse341-p02.onrender.com/users/646913d5128edb848723d22c
### CREATE USER
POST https://cse341-p02.onrender.com/users HTTP/1.1
Content-Type: application/json

{
    "username":"dummyaccount",
    "displayname":"Dummy Account",
    "email":"ImJustHereToTest@mailplace.com",
    "password":"testingtesting123",
    "birthday":"12/25/1983"
    //"description":"Everyone will watch Splatoon 2 let's plays by Eggman"
}
### EDIT USER
PUT https://cse341-p02.onrender.com/users/647257cd576b56365908775c HTTP/1.1
Content-Type: application/json

{
    "username":"dummyaccount",
    //"displayname":"Dummy Account",
    "email":"CrashTestDummy@mailplace.com",
    "password":"testingtesting123",
    "birthday":"12/25/1983",
    "description":"Everyone will watch Splatoon 2 let's plays by Eggman"
}
### DELETE USER
DELETE https://cse341-p02.onrender.com/users/647257cd576b56365908775c HTTP/1.1